version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    restart: always
    ports:
      - "8888:88"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: chat_app
      DB_USER: chat_user
      DB_PASSWORD: chat_password
volumes:
  db-data:
